In [1]:
import pandas as pd
from imblearn.over_sampling import SMOTE

In [2]:
df = pd.read_csv('./Test_02.csv')

In [3]:
df[:3]

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,6.999765,219.143373,16078.45939,7.652135,355.688892,282.502338,17.297556,65.065069,3.360131,1
1,6.897923,173.390928,16616.51662,6.352934,329.339768,337.436088,12.446976,60.159413,4.490105,1
2,6.382315,212.838514,24259.75167,7.360504,333.775777,342.581444,12.332979,67.748991,2.881370,1

In [4]:
target = 'Potability'
X, y = df.drop(target, axis=1), df[target]

sampling_df = None # sampling_df 초기화
X_over_resampled, y_over_resampled = SMOTE().fit_resample(X, y)          # sampling_strategy 옵션: 'auto', sampling_strategy
sampling_df = X_over_resampled
sampling_df[target] = y_over_resampled

In [5]:
print(len(df))
print(len(sampling_df))

1777
1996

In [6]:
df_before = df
df_after = sampling_df

# df_before['state'] = 'Before'
# df_after['state'] = 'After'

In [11]:
column = df_before.columns
test = []
for idx, col in enumerate(df_before.columns):
        combined_df = pd.DataFrame({
            col: df_before[col],
            'sampled_' + col : df_after[col]
        })
        test.append(combined_df)

In [12]:
test

[            ph  sampled_ph
 0     6.999765    6.999765
 1     6.897923    6.897923
 2     6.382315    6.382315
 3     9.917092    9.917092
 4     5.609025    5.609025
 ...        ...         ...
 1991       NaN    6.938039
 1992       NaN    6.602067
 1993       NaN    8.024663
 1994       NaN    6.948333
 1995       NaN    6.422643

 [1996 rows x 2 columns],
         Hardness  sampled_Hardness
 0     219.143373        219.143373
 1     173.390928        173.390928
 2     212.838514        212.838514
 3     196.603746        196.603746
 4     271.630824        271.630824
 ...          ...               ...
 1991         NaN        216.992294
 1992         NaN        202.596201
 1993         NaN        126.517664
 1994         NaN        218.477737
 1995         NaN        145.214304

 [1996 rows x 2 columns],
            Solids  sampled_Solids
 0     16078.45939    16078.459390
 1     16616.51662    16616.516620
 2     24259.75167    24259.751670
 3     37215.22684    37215.226840
 4     26955.33018    26955.330180
 ...           ...             ...
 1991          NaN    19024.171751
 1992          NaN    31983.331933
 1993          NaN     7777.697392
 1994          NaN    18972.499504
 1995          NaN    18075.467025

 [1996 rows x 2 columns],
       Chloramines  sampled_Chloramines
 0        7.652135             7.652135
 1        6.352934             6.352934
 2        7.360504             7.360504
 3        7.408018             7.408018
 4        6.772753             6.772753
 ...           ...                  ...
 1991          NaN             3.267380
 1992          NaN             7.480410
 1993          NaN             8.761846
 1994          NaN             7.211076
 1995          NaN             8.349061

 [1996 rows x 2 columns],
          Sulfate  sampled_Sulfate
 0     355.688892       355.688892
 1     329.339768       329.339768
 2     333.775777       333.775777
 3     247.934855       247.934855
 4     296.651564       296.651564
 ...          ...              ...
 1991         NaN       317.124231
 1992         NaN       316.563374
 1993         NaN       339.159954
 1994         NaN       324.845993
 1995         NaN       411.754999

 [1996 rows x 2 columns],
       Conductivity  sampled_Conductivity
 0       282.502338            282.502338
 1       337.436088            337.436088
 2       342.581444            342.581444
 3       522.548553            522.548553
 4       443.872558            443.872558
 ...            ...                   ...
 1991           NaN            445.429160
 1992           NaN            293.884393
 1993           NaN            555.392400
 1994           NaN            338.644591
 1995           NaN            329.106850

 [1996 rows x 2 columns],
       Organic_carbon  sampled_Organic_carbon
 0          17.297556               17.297556
 1          12.446976               12.446976
 2          12.332979               12.332979
 3           5.512040                5.512040
 4          17.048683               17.048683
 ...              ...                     ...
 1991             NaN               13.007080
 1992             NaN               11.501734
 1993             NaN               13.302448
 1994             NaN               16.774351
 1995             NaN               13.056762

 [1996 rows x 2 columns],
       Trihalomethanes  sampled_Trihalomethanes
 0           65.065069                65.065069
 1           60.159413                60.159413
 2           67.748991                67.748991
 3           77.830816                77.830816
 4           72.827392                72.827392
 ...               ...                      ...
 1991              NaN                77.042047
 1992              NaN                65.350156
 1993              NaN                73.074686
 1994              NaN                81.211522
 1995              NaN                59.476123

 [1996 rows x 2 columns],
       Turbidity  sampled_Turbidity
 0      3.360131           3.360131
 1      4.490105           4.490105
 2      2.881370           2.881370
 3      3.393325           3.393325
 4      3.354890           3.354890
 ...         ...                ...
 1991        NaN           2.087918
 1992        NaN           4.244291
 1993        NaN           4.370329
 1994        NaN           4.803107
 1995        NaN           3.941877

 [1996 rows x 2 columns],
       Potability  sampled_Potability
 0            1.0                   1
 1            1.0                   1
 2            1.0                   1
 3            1.0                   1
 4            1.0                   1
 ...          ...                 ...
 1991         NaN                   1
 1992         NaN                   1
 1993         NaN                   1
 1994         NaN                   1
 1995         NaN                   1

 [1996 rows x 2 columns]]